codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 5%
        informational: false
        if_ci_failed: error
    
    patch:
      default:
        target: 80%
        threshold: 10%
        informational: true
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/"
  - "target/"
  - "docs/"
  - "scripts/"
  - "k8s/"
  - "src/bin/"
  - "**/*.test.rs"
  - "**/tests.rs"

flags:
  unit:
    paths:
      - "src/"
    carryforward: true
  
  integration:
    paths:
      - "src/"
    carryforward: true
