apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-auth-rs
  labels:
    app.kubernetes.io/part-of: ldap-auth
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ldap-auth-rs
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
