name: Spellcheck

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Check spelling
        uses: crate-ci/typos@8a48f81b6c64dcfea44b3633223084c4be58ac5f
        with:
          files: |
            ./src
            ./tests
            ./docs
            ./README.md
            ./CONTRIBUTING.md
          config: ./.typos.toml
